openapi: 3.0.3
info:
  title: Morpheus API
  description: |-
    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.

    This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
  version: 5.5.2
  termsOfService: https://morpheusdata.com/terms-and-conditions/
  contact:
    email: dev@morpheusdata.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://{api_url}
    description: Morpheus API
    variables:
      api_url:
        default: localhost
paths:
  /api/accounts:
    $ref: paths/api@accounts.yaml
  /api/accounts/{id}:
    $ref: paths/api@accounts@id.yaml
  /api/activity:
    $ref: paths/api@activity.yaml
  /api/accounts/available-roles:
    $ref: paths/api@accounts@available-roles.yaml
  /api/approval-items/{id}:
    $ref: paths/api@approval-items@id.yaml
  /api/approval-items/{id}/{action}:
    $ref: paths/api@approval-items@id@action.yaml
  /api/approvals:
    $ref: paths/api@approvals.yaml
  /api/approvals/{id}:
    $ref: paths/api@approvals@id.yaml
  /api/apps/{id}/wiki:
    $ref: paths/api@apps@id@wiki.yaml
  /api/budgets:
    $ref: paths/api@budgets.yaml
  /api/budgets/{id}:
    $ref: paths/api@budgets@id.yaml
  /api/clusters/{id}/wiki:
    $ref: paths/api@clusters@id@wiki.yaml
  /api/credentials:
    $ref: paths/api@credentials.yaml
  /api/credentials/{id}:
    $ref: paths/api@credentials@id.yaml
  /api/dashboard:
    $ref: paths/api@dashboard.yaml
  /api/doc:
    $ref: paths/api@doc.yaml
  /api/doc/openapi:
    $ref: paths/api@doc@openapi.yaml
  /api/doc/openapi.yaml:
    $ref: paths/api@doc@openapi.yaml.yaml
  /api/environments:
    $ref: paths/api@environments.yaml
  /api/environments/{id}:
    $ref: paths/api@environments@id.yaml
  /api/environments/{id}/toggle-active:
    $ref: paths/api@environments@id@toggle-active.yaml
  /api/forgot/reset-password:
    $ref: paths/api@forgot@reset-password.yaml
  /api/forgot/send-email:
    $ref: paths/api@forgot@send-email.yaml
  /api/groups:
    $ref: paths/api@groups.yaml
  /api/groups/{id}:
    $ref: paths/api@groups@id.yaml
  /api/groups/{id}/update-zones:
    $ref: paths/api@groups@id@update-zones.yaml
  /api/groups/{id}/wiki:
    $ref: paths/api@groups@id@wiki.yaml
  /api/instances:
    $ref: paths/api@instances.yaml
  /api/instances/{id}:
    $ref: paths/api@instances@id.yaml
  /api/instances/{id}/apply:
    $ref: paths/api@instances@id@apply.yaml
  /api/instances/{id}/backup:
    $ref: paths/api@instances@id@backup.yaml
  /api/instances/{id}/backups:
    $ref: paths/api@instances@id@backups.yaml
  /api/instances/{id}/clone:
    $ref: paths/api@instances@id@clone.yaml
  /api/instances/{id}/clone-image:
    $ref: paths/api@instances@id@clone-image.yaml
  /api/instances/{id}/cancel-expiration:
    $ref: paths/api@instances@id@cancel-expiration.yaml
  /api/instances/{id}/cancel-removal:
    $ref: paths/api@instances@id@cancel-removal.yaml
  /api/instances/{id}/cancel-shutdown:
    $ref: paths/api@instances@id@cancel-shutdown.yaml
  /api/instances/{id}/containers:
    $ref: paths/api@instances@id@containers.yaml
  /api/instances/{id}/delete-container-snapshots/{containerId}:
    $ref: paths/api@instances@id@delete-container-snapshots@id.yaml
  /api/instances/{id}/delete-all-snapshots:
    $ref: paths/api@instances@id@delete-all-snapshots.yaml
  /api/instances/{id}/envs:
    $ref: paths/api@instances@id@envs.yaml
  /api/instances/{id}/extend-expiration:
    $ref: paths/api@instances@id@extend-expiration.yaml
  /api/instances/{id}/extend-shutdown:
    $ref: paths/api@instances@id@extend-shutdown.yaml
  /api/instances/{id}/history:
    $ref: paths/api@instances@id@history.yaml
  /api/instances/{id}/import-snapshot:
    $ref: paths/api@instances@id@import-snapshot.yaml
  /api/instances/{id}/linked-clone/{snapshotId}:
    $ref: paths/api@instances@id@linked-clone@id.yaml
  /api/instances/{id}/lock:
    $ref: paths/api@instances@id@lock.yaml
  /api/instances/{id}/prepare-apply:
    $ref: paths/api@instances@id@prepare-apply.yaml
  /api/instances/{id}/resize:
    $ref: paths/api@instances@id@resize.yaml
  /api/instances/{id}/restart:
    $ref: paths/api@instances@id@restart.yaml
  /api/instances/{id}/revert-snapshot/{snapshotId}:
    $ref: paths/api@instances@id@revert-snapshot@id.yaml
  /api/instances/{id}/security-groups:
    $ref: paths/api@instances@id@security-groups.yaml
  /api/instances/{id}/snapshot:
    $ref: paths/api@instances@id@snapshot.yaml
  /api/instances/{id}/snapshots:
    $ref: paths/api@instances@id@snapshots.yaml
  /api/instances/{id}/start:
    $ref: paths/api@instances@id@start.yaml
  /api/instances/{id}/state:
    $ref: paths/api@instances@id@state.yaml
  /api/instances/{id}/stop:
    $ref: paths/api@instances@id@stop.yaml
  /api/instances/{id}/unlock:
    $ref: paths/api@instances@id@unlock.yaml
  /api/instances/{id}/wiki:
    $ref: paths/api@instances@id@wiki.yaml
  /api/instances/{id}/workflow:
    $ref: paths/api@instances@id@workflow.yaml
  /api/instances/service-plans:
    $ref: paths/api@instances@service-plans.yaml
  /api/instances/{id}/validate-apply:
    $ref: paths/api@instances@id@validate-apply.yaml
  /api/instance-types:
    $ref: paths/api@instance-types.yaml
  /api/instance-types/{id}:
    $ref: paths/api@instance-types@id.yaml
  /api/invoices:
    $ref: paths/api@invoices.yaml
  /api/invoices/{id}:
    $ref: paths/api@invoices@id.yaml
  /api/invoice-line-items:
    $ref: paths/api@invoice-line-items.yaml
  /api/invoice-line-items/{id}:
    $ref: paths/api@invoice-line-items@id.yaml
  /api/license:
    $ref: paths/api@license.yaml
  /api/log-settings:
    $ref: paths/api@log-settings.yaml
  /api/log-settings/syslog-rules:
    $ref: paths/api@log-settings@syslog-rules.yaml
  /api/log-settings/syslog-rules/{id}:
    $ref: paths/api@log-settings@syslog-rules@id.yaml
  /api/logs:
    $ref: paths/api@logs.yaml
  /api/key-pairs:
    $ref: paths/api@key-pairs.yaml
  /api/key-pairs/{id}:
    $ref: paths/api@key-pairs@id.yaml
  /api/library/option-types:
    $ref: paths/api@library@option-types.yaml
  /api/library/option-types/{id}:
    $ref: paths/api@library@option-types@id.yaml
  /api/library/instance-types:
    $ref: paths/api@library@instance-types.yaml
  /api/library/instance-types/{id}:
    $ref: paths/api@library@instance-types@id.yaml
  /api/library/instance-types/{id}/toggle-featured:
    $ref: paths/api@library@instance-types@id@toggle-featured.yaml
  /api/library/instance-types/{id}/update-logo:
    $ref: paths/api@library@instance-types@id@update-logo.yaml
  /api/license/test:
    $ref: paths/api@license@test.yaml
  /api/monitoring/alerts:
    $ref: paths/api@monitoring@alerts.yaml
  /api/monitoring/alerts/{id}:
    $ref: paths/api@monitoring@alerts@id.yaml
  /api/monitoring/apps:
    $ref: paths/api@monitoring@apps.yaml
  /api/monitoring/apps/mute-all:
    $ref: paths/api@monitoring@apps@mute-all.yaml
  /api/monitoring/apps/{id}:
    $ref: paths/api@monitoring@apps@id.yaml
  /api/monitoring/apps/{id}/mute:
    $ref: paths/api@monitoring@apps@id@mute.yaml
  /api/monitoring/checks:
    $ref: paths/api@monitoring@checks.yaml
  /api/monitoring/checks/mute-all:
    $ref: paths/api@monitoring@checks@mute-all.yaml
  /api/monitoring/checks/{id}:
    $ref: paths/api@monitoring@checks@id.yaml
  /api/monitoring/checks/{id}/mute:
    $ref: paths/api@monitoring@checks@id@mute.yaml
  /api/monitoring/check-types:
    $ref: paths/api@monitoring@check-types.yaml
  /api/monitoring/check-types/{id}:
    $ref: paths/api@monitoring@check-types@id.yaml
  /api/monitoring/contacts:
    $ref: paths/api@monitoring@contacts.yaml
  /api/monitoring/contacts/{id}:
    $ref: paths/api@monitoring@contacts@id.yaml
  /api/monitoring/groups:
    $ref: paths/api@monitoring@groups.yaml
  /api/monitoring/groups/{id}:
    $ref: paths/api@monitoring@groups@id.yaml
  /api/monitoring/groups/{id}/mute:
    $ref: paths/api@monitoring@groups@id@mute.yaml
  /api/monitoring/incidents:
    $ref: paths/api@monitoring@incidents.yaml
  /api/monitoring/incidents/{id}:
    $ref: paths/api@monitoring@incidents@id.yaml
  /api/monitoring/incidents/{id}/mute:
    $ref: paths/api@monitoring@incidents@id@mute.yaml
  /api/monitoring/incidents/{id}/reopen:
    $ref: paths/api@monitoring@incidents@id@reopen.yaml
  /api/monitoring/incidents/mute-all:
    $ref: paths/api@monitoring@incidents@mute-all.yaml
  /api/network-types:
    $ref: paths/api@network-types.yaml
  /api/network-types/{id}:
    $ref: paths/api@network-types@id.yaml
  /api/networks:
    $ref: paths/api@networks.yaml
  /api/networks/{id}:
    $ref: paths/api@networks@id.yaml
  /api/networks/{id}/routes:
    $ref: paths/api@networks@id@routes.yaml
  /api/networks/{id}/routes/{routeId}:
    $ref: paths/api@networks@id@routes@id.yaml
  /api/networks/servers/{serverId}/dhcp-relays:
    $ref: paths/api@networks@servers@id@dhcp-relays.yaml
  /api/networks/servers/{serverId}/dhcp-relays/{id}:
    $ref: paths/api@networks@servers@id@dhcp-relays@id.yaml
  /api/networks/servers/{serverId}/dhcp-servers:
    $ref: paths/api@networks@servers@id@dhcp-servers.yaml
  /api/networks/servers/{serverId}/dhcp-servers/{id}:
    $ref: paths/api@networks@servers@id@dhcp-servers@id.yaml
  /api/networks/servers/{serverId}/edge-clusters:
    $ref: paths/api@networks@servers@id@edge-clusters.yaml
  /api/networks/servers/{serverId}/edge-clusters/{id}:
    $ref: paths/api@networks@servers@id@edge-clusters@id.yaml
  /api/networks/servers/{serverId}/firewall-rules:
    $ref: paths/api@networks@servers@id@firewall-rules.yaml
  /api/networks/servers/{serverId}/firewall-rules/{id}:
    $ref: paths/api@networks@servers@id@firewall-rules@id.yaml
  /api/ping:
    $ref: paths/api@ping.yaml
  /api/processes:
    $ref: paths/api@processes.yaml
  /api/processes/{id}:
    $ref: paths/api@processes@id.yaml
  /api/processes/events/{id}:
    $ref: paths/api@processes@events@id.yaml
  /api/provision-types:
    $ref: paths/api@provision-types.yaml
  /api/provision-types/{id}:
    $ref: paths/api@provision-types@id.yaml
  /api/report-types:
    $ref: paths/api@report-types.yaml
  /api/reports:
    $ref: paths/api@reports.yaml
  /api/reports/{id}:
    $ref: paths/api@reports@id.yaml
  /api/reports/download/{id}{format}:
    $ref: paths/api@reports@download@id.yaml
  /api/roles:
    $ref: paths/api@roles.yaml
  /api/roles/{id}:
    $ref: paths/api@roles@id.yaml
  /api/search:
    $ref: paths/api@search.yaml
  /api/servers/{id}/wiki:
    $ref: paths/api@servers@id@wiki.yaml
  /api/setup:
    $ref: paths/api@setup.yaml
  /api/snapshots/{id}:
    $ref: paths/api@snapshots@id.yaml
  /api/usage:
    $ref: paths/api@usage.yaml
  /api/users:
    $ref: paths/api@users.yaml
  /api/users/{id}:
    $ref: paths/api@users@id.yaml
  /api/users/available-roles:
    $ref: paths/api@users@available-roles.yaml
  /api/vdi:
    $ref: paths/api@vdi.yaml
  /api/vdi/{id}:
    $ref: paths/api@vdi@id.yaml
  /api/vdi/{id}/allocate:
    $ref: paths/api@vdi@id@allocate.yaml
  /api/whoami:
    $ref: paths/api@whoami.yaml
  /api/wiki/categories:
    $ref: paths/api@wiki@categories.yaml
  /api/wiki/pages:
    $ref: paths/api@wiki@pages.yaml
  /api/wiki/pages/{id}:
    $ref: paths/api@wiki@pages@id.yaml
  /api/zone-types:
    $ref: paths/api@zone-types.yaml
  /api/zone-types/{id}:
    $ref: paths/api@zone-types@id.yaml
  /api/zones:
    $ref: paths/api@zones.yaml
  /api/zones/{id}:
    $ref: paths/api@zones@id.yaml
  /api/zones/{id}/refresh:
    $ref: paths/api@zones@id@refresh.yaml
  /api/zones/{id}/security-groups:
    $ref: paths/api@zones@id@security-groups.yaml
  /api/zones/{id}/wiki:
    $ref: paths/api@zones@id@wiki.yaml
  /oauth/token:
    $ref: paths/oauth@token.yaml
components:
  securitySchemes:
    bearerAuth:
      description: Populate a bearer token for the Morpheus appliance you are testing
      type: http
      scheme: bearer
security:
  - bearerAuth: []
externalDocs:
  url: https://docs.morpheusdata.com
tags:
  - name: Administration
    description: All Endpoints Under the Administration Tab
  - name: Activity
    description: Manage Appliance Activity Logs
  - name: Alerts
    description: Manage Alerts
  - name: Appliance Settings
    description: Manage Appliance Settings
  - name: Approvals
    description: Manage Approvals
  - name: Apps
    description: Manage Apps
  - name: Archives
    description: Manage Archives
  - name: Authentication
    description: Manage Appliance Authentication
  - name: Automation
    description: Manage Tasks and Workflows
  - name: Backup Settings
    description: Manage Backup Settings
  - name: Billing
    description: Manage Billing
  - name: Blueprints
    description: Manage Blueprints
  - name: Budgets
    description: Manage Budgets
  - name: Checks
    description: Manage Monitoring Checks
  - name: Clouds
    description: Manage Clouds
  - name: Cluster Layouts
    description: Manage Cluster Layouts
  - name: Clusters
    description: Manage Kubernetes Clusters
  - name: Contacts
    description: Manage Monitoring Contacts
  - name: Credentials
    description: Manage Credentials
  - name: Cypher
    description: Manage Cypher
  - name: Dashboard
    description: View Dashboard Details
  - name: Deployments
    description: Manage File Deployments
  - name: Deploys
    description: Manage Deploys
  - name: Documentation
    description: >-
      View documentation for your [Morpheus Data](https://morpheusdata.com)
      appliance.
  - name: Environments
    description: Manage Environments
  - name: File Templates
    description: Manage File Templates
  - name: Groups
    description: Manage Groups
  - name: Guidance
    description: Manage Guidance Recommendations
  - name: Health
    description: View Appliance Health Statistics
  - name: History
    description: View History
  - name: Identity Sources
    description: Manage Identity Sources
  - name: Image Builds
    description: Manage Image Builds
  - name: Incidents
    description: Manage Ticket Incidents
  - name: Infrastructure
    description: All Endpoints Under the Infrastructure Tab
  - name: Inputs
    description: Manage Inputs (Option Types)
  - name: Instance Types
    description: Manage Instance Types
  - name: Instances
    description: Manage Instances
  - name: Integrations
    description: Manage Integrations
  - name: Invoices
    description: Manage Invoices
  - name: Jobs
    description: Manage Jobs
  - name: Key Pairs
    description: Manage Key Pairs
  - name: Layouts
    description: Manage Layouts
  - name: Library
    description: All Endpoints Under the Library Tab
  - name: License
    description: Manage Appliance License
  - name: Load Balancers
    description: Manage Load Balancers
  - name: Log Settings
    description: Manage Log Settings
  - name: Logs
    description: View Logs
  - name: Monitoring
    description: All Endpoints Under the Monitoring Tab
  - name: Morpheus API
    description: All Endpoints Specific to Morpheus API
  - name: Networks
    description: Manage Networks
  - name: Node Types
    description: Manage Node/VM Types
  - name: Operations
    description: All Endpoints Under the Operations Tab
  - name: Option Lists
    description: Manage Option Lists
  - name: Options
    description: Manage Options
  - name: Personas
    description: All Endpoints Pertaining to Personas
  - name: Ping
    description: Ping Appliance
  - name: Policies
    description: Manage Policies
  - name: Price Sets
    description: Manage Price Sets
  - name: Prices
    description: Manage Prices
  - name: Projects
    description: Manage Projects
  - name: Provisioning
    description: All Endpoints Under the Provisioning Tab
  - name: Provisioning Settings
    description: Manage Provisioning Settings
  - name: Provisioning Licenses
    description: Manage Provisioning Licenses
  - name: Reports
    description: Manage Reports
  - name: Roles
    description: Manage Roles (Authorities)
  - name: Scripts
    description: Manage Scripts
  - name: Search
    description: Global Search Functions
  - name: Security Groups
    description: Manage Security Groups
  - name: Self Service
    description: Manage Self Service
  - name: Servers
    description: Manage Servers (Hosts)
  - name: Service Catalog
    description: Manage Service Catalog
  - name: Service Plans
    description: Manage Service Plans
  - name: Setup
    description: Setup New Appliance
  - name: Spec Templates
    description: Manage Spec Templates
  - name: SSL Certificates
    description: Manage SSL Certificates
  - name: Storage
    description: Manage Storage
  - name: Tenants
    description: Manage Tenants (Accounts)
  - name: Tools
    description: All Endpoints Under the Tools Tab
  - name: Usage
    description: View Usage
  - name: Users
    description: Manage Users
  - name: VDI
    description: Manage VDI Pools & Desktops
  - name: Virtual Images
    description: Manage Virtual Images
  - name: Whitelabel Settings
    description: Manage Whitelabelling
  - name: Wiki
    description: Manage Wiki