openapi: 3.0.3
info:
  title: Morpheus API
  description: |-
    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.

    This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
  version: 5.4.4
  termsOfService: https://morpheusdata.com/terms-and-conditions/
  contact:
    email: dev@morpheusdata.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://{api_url}
    description: Morpheus API
    variables:
      api_url:
        default: ""
      application_name:
        default: Morpheus
      company_name:
        default: Morpheus Data
      company_website:
        default: https://www.morpheusdata.com
      company_domain:
        default: morpheusdata.com
paths:
  /api/accounts:
    $ref: paths/api@accounts.yaml
  /api/accounts/{id}:
    $ref: paths/api@accounts@id.yaml
  /api/activity:
    $ref: paths/api@activity.yaml
  /api/accounts/available-roles:
    $ref: paths/api@accounts@available-roles.yaml
  /api/approval-items/{id}:
    $ref: paths/api@approval-items@id.yaml
  /api/approval-items/{id}/{action}:
    $ref: paths/api@approval-items@id@action.yaml
  /api/approvals:
    $ref: paths/api@approvals.yaml
  /api/approvals/{id}:
    $ref: paths/api@approvals@id.yaml
  /api/apps/{id}/wiki:
    $ref: paths/api@apps@id@wiki.yaml
  /api/budgets:
    $ref: paths/api@budgets.yaml
  /api/budgets/{id}:
    $ref: paths/api@budgets@id.yaml
  /api/clusters/{id}/wiki:
    $ref: paths/api@clusters@id@wiki.yaml
  /api/dashboard:
    $ref: paths/api@dashboard.yaml
  /api/doc:
    $ref: paths/api@doc.yaml
  /api/doc/openapi:
    $ref: paths/api@doc@openapi.yaml
  /api/doc/openapi.yaml:
    $ref: paths/api@doc@openapi.yaml.yaml
  /api/forgot/reset-password:
    $ref: paths/api@forgot@reset-password.yaml
  /api/forgot/send-email:
    $ref: paths/api@forgot@send-email.yaml
  /api/groups:
    $ref: paths/api@groups.yaml
  /api/groups/{id}:
    $ref: paths/api@groups@id.yaml
  /api/groups/{id}/update-zones:
    $ref: paths/api@groups@id@update-zones.yaml
  /api/groups/{id}/wiki:
    $ref: paths/api@groups@id@wiki.yaml
  /api/instances/{id}/wiki:
    $ref: paths/api@instances@id@wiki.yaml
  /api/license:
    $ref: paths/api@license.yaml
  /api/license/test:
    $ref: paths/api@license@test.yaml
  /api/ping:
    $ref: paths/api@ping.yaml
  /api/processes:
    $ref: paths/api@processes.yaml
  /api/processes/{id}:
    $ref: paths/api@processes@id.yaml
  /api/processes/events/{id}:
    $ref: paths/api@processes@events@id.yaml
  /api/provision-types:
    $ref: paths/api@provision-types.yaml
  /api/provision-types/{id}:
    $ref: paths/api@provision-types.yaml
  /api/report-types:
    $ref: paths/api@report@types.yaml
  /api/reports:
    $ref: paths/api@reports.yaml
  /api/reports/{id}:
    $ref: paths/api@reports@id.yaml
  /api/reports/download/{id}{format}:
    $ref: paths/api@reports@download@id.yaml
  /api/roles:
    $ref: paths/api@roles.yaml
  /api/roles/{id}:
    $ref: paths/api@roles@id.yaml
  /api/search:
    $ref: paths/api@search.yaml
  /api/servers/{id}/wiki:
    $ref: paths/api@servers@id@wiki.yaml
  /api/setup:
    $ref: paths/api@setup.yaml
  /api/usage:
    $ref: paths/api@usage.yaml
  /api/users:
    $ref: paths/api@users.yaml
  /api/users/{id}:
    $ref: paths/api@users@id.yaml
  /api/users/available-roles:
    $ref: paths/api@users@available-roles.yaml
  /api/whoami:
    $ref: paths/api@whoami.yaml
  /api/wiki/categories:
    $ref: paths/api@wiki@categories.yaml
  /api/wiki/pages:
    $ref: paths/api@wiki@pages.yaml
  /api/wiki/pages/{id}:
    $ref: paths/api@wiki@pages@id.yaml
  /api/zones/{id}/wiki:
    $ref: paths/api@zones@id@wiki.yaml
  /oauth/token:
    $ref: paths/oauth@token.yaml
components:
  securitySchemes:
    bearerAuth:
      description: Populate a bearer token for the Morpheus appliance you are testing
      type: http
      scheme: bearer
security:
  - bearerAuth: []
externalDocs:
  url: https://docs.morpheusdata.com
tags:
  - name: Activity
    description: Manage Appliance Activity Logs
  - name: Alerts
    description: Manage Alerts
  - name: Appliance Settings
    description: Manage Appliance Settings
  - name: Approvals
    description: Manage Approvals
  - name: Apps
    description: Manage Apps
  - name: Archives
    description: Manage Archives
  - name: Authentication
    description: Manage Appliance Authentication
  - name: Automation
    description: Manage Tasks and Workflows
  - name: Backup Settings
    description: Manage Backup Settings
  - name: Billing
    description: Manage Billing
  - name: Blueprints
    description: Manage Blueprints
  - name: Budgets
    description: Manage Budgets
  - name: Checks
    description: Manage Monitoring Checks
  - name: Clouds
    description: Manage Clouds
  - name: Cluster Layouts
    description: Manage Cluster Layouts
  - name: Clusters
    description: Manage Kubernetes Clusters
  - name: Contacts
    description: Manage Monitoring Contacts
  - name: Cypher
    description: Manage Cypher
  - name: Dashboard
    description: View Dashboard Details
  - name: Deployments
    description: Manage File Deployments
  - name: Deploys
    description: Manage Deploys
  - name: Documentation
    description: >-
      View documentation for your [Morpheus Data](https://morpheusdata.com)
      appliance.
  - name: Environments
    description: Manage Environments
  - name: File Templates
    description: Manage File Templates
  - name: Groups
    description: Manage Groups
  - name: Guidance
    description: Manage Guidance Recommendations
  - name: Health
    description: View Appliance Health Statistics
  - name: History
    description: View History
  - name: Identity Sources
    description: Manage Identity Sources
  - name: Image Builds
    description: Manage Image Builds
  - name: Incidents
    description: Manage Ticket Incidents
  - name: Inputs
    description: Manage Inputs (Option Types)
  - name: Instance Types
    description: Manage Instance Types
  - name: Instances
    description: Manage Instances
  - name: Integrations
    description: Manage Integrations
  - name: Invoices
    description: Manage Invoices
  - name: Jobs
    description: Manage Jobs
  - name: Key Pairs
    description: Manage Key Pairs
  - name: Layouts
    description: Manage Layouts
  - name: License
    description: Manage Appliance License
  - name: Load Balancers
    description: Manage Load Balancers
  - name: Log Settings
    description: Manage Log Settings
  - name: Logs
    description: View Logs
  - name: Monitoring
    description: Manage Monitoring
  - name: Networks
    description: Manage Networks
  - name: Node Types
    description: Manage Node/VM Types
  - name: Option Lists
    description: Manage Option Lists
  - name: Options
    description: Manage Options
  - name: Personas
    description: Manage Personas
  - name: Ping
    description: Ping Appliance
  - name: Policies
    description: Manage Policies
  - name: Price Sets
    description: Manage Price Sets
  - name: Prices
    description: Manage Prices
  - name: Projects
    description: Manage Projects
  - name: Provisioning
    description: Manage Provisioning
  - name: Provisioning Settings
    description: Manage Provisioning Settings
  - name: Provisioning Licenses
    description: Manage Provisioning Licenses
  - name: Reports
    description: Manage Reports
  - name: Roles
    description: Manage Roles (Authorities)
  - name: Scripts
    description: Manage Scripts
  - name: Search
    description: Global Search Functions
  - name: Security Groups
    description: Manage Security Groups
  - name: Self Service
    description: Manage Self Service
  - name: Servers
    description: Manage Servers (Hosts)
  - name: Service Catalog
    description: Manage Service Catalog
  - name: Service Plans
    description: Manage Service Plans
  - name: Setup
    description: Setup New Appliance
  - name: Spec Templates
    description: Manage Spec Templates
  - name: SSL Certificates
    description: Manage SSL Certificates
  - name: Storage
    description: Manage Storage
  - name: Tenants
    description: Manage Tenants (Accounts)
  - name: Usage
    description: View Usage
  - name: Users
    description: Manage Users
  - name: VDI Pools
    description: Manage VDI Pools
  - name: Virtual Desktop
    description: Manage Virtual Desktops
  - name: Virtual Images
    description: Manage Virtual Images
  - name: Whitelabel Settings
    description: Manage Whitelabelling
  - name: Wiki
    description: Manage Wiki