required:
  - name
  - type
  - username
  - password
  - authKey
properties:
  type:
    type: string
    description: Credential Type Code
    enum:
      - username-password-keypair
  name: 
    type: string
    description: A unique name scoped to your account for the credential
  description:
    type: string
    description: Optional Description
  enabled:
    type: boolean
    description: Credential enabled
    default: true
  integration:
    type: object
    description: |
      Credential Store. ID of a Credential Integration. This can be set to store the credential in an external store.
    nullable: true
    properties:
      id:
        oneOf:
          - type: string
          - type: integer
            format: int64
  username:
    type: string
    description: Username
    example: your_user
  password:
    type: string
    description: User password, API Key, or applicable secret
    example: myPassword
  authKey:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        description: Private Key ID of a `Key Pair`
        example: 9