required:
  - name
  - type
  - username
  - password
properties:
  type:
    type: string
    description: Credential Type Code
    enum:
      - username-api-key
  name: 
    type: string
    description: A unique name scoped to your account for the credential
  description:
    type: string
    description: Optional Description
  enabled:
    type: boolean
    description: Credential enabled
    default: true
  integration:
    type: object
    description: |
      Credential Store. ID of a Credential Integration. 
      This can be set to store the credential in an external store.
      The default is `Internal`.
    nullable: true
    properties:
      id:
        oneOf:
          - type: string
            default: Internal
          - type: integer
            format: int64
  username:
    type: string
    description: Username
    example: your_user
  password:
    type: string
    description: API Key
    example: your_api_key