required:
  - name
  - type
  - config
properties:
  type:
    type: string
    description: Credential Type Code
    enum:
      - oauth2
  name: 
    type: string
    description: A unique name scoped to your account for the credential
  description:
    type: string
    description: Optional Description
  enabled:
    type: boolean
    description: Credential enabled
    default: true
  integration:
    type: object
    description: |
      Credential Store. ID of a Credential Integration. 
      This can be set to store the credential in an external store.
      The default is `Internal`.
    nullable: true
    properties:
      id:
        oneOf:
          - type: string
            default: Internal
          - type: integer
            format: int64
  username:
    type: string
    description: Username
    example: jsmith
  password:
    type: string
    description: Password
    example: myPassword
  config:
    type: object
    required:
      - grantType
      - accessTokenUrl
      - clientAuth
    properties:
      grantType:
        type: string
        description: OAuth 2.0 grant type
        enum:
        - password
        - client_credentials
      accessTokenUrl:
        type: string
        description: Token endpoint
        example: 'https://example.com'
      clientId:
        type: string
        description: Client ID
        example: myclientid12345
      clientSecret:
        type: string
        description: Client Secret
        example: myclientsecret12345
      scope:
        type: string
        description: Scope
        example: read
      clientAuth:
        type: string
        description: Client Authentication Method
        enum:
        - body
        - basic-auth