type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  description: 
    type: string
  accountId: 
    type: integer
    format: int64
  externalId: 
    type: string
    nullable: true
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
  versionCount: 
    type: integer
    format: int64
  versions: 
    type: array
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        deployType: 
          type: string
        fetchUrl: 
          type: string
          nullable: true
        gitUrl: 
          type: string
          nullable: true
        gitRef: 
          type: string
          nullable: true
        userVersion: 
          type: string
        version: 
          type: string
        status: 
          type: string
        dateCreated: 
          type: string
          format: date-time
        lastUpdated: 
          type: string
          format: date-time
