type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  description: 
    type: string
  code: 
    type: string
  type: 
    type: string
  active: 
    type: boolean
  deleted: 
    type: boolean
  autoSyncOnLogin: 
    type: boolean
  externalLogin: 
    type: boolean
  allowCustomMappings: 
    type: boolean
  account: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
  defaultAccountRole: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
      authority: 
        type: string
  config: 
    type: object
    properties: 
      url: 
        type: string
      logoutUrl: 
        type: string
      doNotIncludeSAMLRequest: 
        type: boolean
      SAMLSignatureMode: 
        type: string
      doNotValidateSignature: 
        type: boolean
      doNotValidateStatusCode: 
        type: boolean
      doNotValidateDestination: 
        type: boolean
      doNotValidateIssueInstants: 
        type: boolean
      doNotValidateAssertions: 
        type: boolean
      givenNameAttribute: 
        type: string
      surnameAttribute: 
        type: string
      emailAttribute: 
        type: string
      requiredAttributeValue: 
        type: string
      roleAttributeName: 
        type: string
      azureTenantId: 
        type: string
      azureAppId: 
        type: string
      azureAppSecret: 
        type: string
        nullable: true
      roleLinkAttributeName: 
        type: string
      publicKey: 
        type: string
      azureAppSecretHash: 
        type: string
        nullable: true
  roleMappings: 
    type: array
    items: 
      type: object
      properties: 
        sourceRoleName: 
          type: string
        sourceRoleFqn: 
          type: string
          nullable: true
        mappedRole: 
          type: object
          properties: 
            id: 
              type: integer
              format: int64
            name: 
              type: string
            authority: 
              type: string
  subdomain: 
    type: string
  loginURL: 
    type: string
  providerSettings: 
    type: object
    properties: 
      entityId: 
        type: string
      acsUrl: 
        type: string
      spMetadata: 
        type: string
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
