type: object
properties: 
  id: 
    type: integer
    format: int64
  accountId: 
    type: integer
    format: int64
  name: 
    type: string
  code: 
    type: string
    nullable: true
  taskType: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      code: 
        type: string
        enum: 
          - jrubyTask
      name: 
        type: string
  labels:
    type: array
    items: 
      type: string
  taskOptions: 
    type: object
    additionalProperties: false
    properties: 
      host: 
        type: string
        nullable: true
      username: 
        type: string
        nullable: true
      localScriptGitId: 
        type: string
        nullable: true
      password: 
        type: string
        nullable: true
      passwordHash: 
        type: string
        nullable: true
      sshKey: 
        type: string
        nullable: true
      port: 
        type: string
        nullable: true
      localScriptGitRef: 
        type: string
        nullable: true
  file: 
    type: object
    nullable: true
    properties: 
      id: 
        type: integer
        format: int64
        nullable: true
      sourceType: 
        type: string
        nullable: true
      contentRef: 
        type: string
        nullable: true
      contentPath: 
        type: string
        nullable: true
      repository: 
        type: object
        nullable: true
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
      content: 
        type: string
        nullable: true
  resultType: 
    type: string
    nullable: true
  executeTarget: 
    type: string
  retryable: 
    type: boolean
  retryCount: 
    type: integer
    format: int64
  retryDelaySeconds: 
    type: integer
    format: int64
  allowCustomConfig: 
    type: boolean
  credential: 
    type: object
    properties: 
      type: 
        type: string
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
